### ISSUE TITLE
Updated Calspec files

### ISSUE THREAD

**Issue by cnaw** [pypeit/PypeIt-development-suite#266]
Hi, 
Thank you all for this great package! I notice that the 
https://pypeit.readthedocs.io/en/release/standards.html
page states  the CALSPEC package as being defunct (the links at stsci  definitely are defunct - for instance this one on 
https://pypeit.readthedocs.io/en/release/fluxing.html)

There have been updates to CALSPEC and the current version (Feb23) can be reached from
https://archive.stsci.edu/hlsps/reference-atlases/cdbs/
following the "current_calspec" link.

I bring this up because I have MMT/Binospec observations of BD+60 1753 (a close analog  to Vega, but without dust), and this is not in the current set of calibrators, which I had selected because it is part of the CALSPEC package and was a bit surprised that it is not there.

Christopher Willmer

**Comment by debora-pe** [comment]
Addressed in PRs https://github.com/pypeit/PypeIt/pull/1799 and https://github.com/pypeit/PypeIt/pull/1805
