### ISSUE TITLE
Problem when reduce the keck_lris_blue data

### ISSUE THREAD

**Issue by fgscc** [pypeit/PypeIt-development-suite#291]
I am trying to reduce the keck_lris_blue data [target coodinate RA, DEC (15:39:32.14, +50:27:38.9)], there are hundreds of the science files, and I am trying to reduce these five files: 
LB.20180617.27634.fits
LB.20180617.28189.fits
LB.20180617.28291.fits
LB.20180617.28380.fits
LB.20180617.28459.fits

The reduction of the file LB.20180617.27634.fits is well done and I can obtian the spectrum. 
But for the rest four files, when the software tries to reduce, the software stoppes, and reports "No trace locations". 

I check the 2D file for these files, and find for LB.20180617.27634.fits, the spectrum seems more obvious than the other four files. Does it means the software can not find the spectrum location to trace?

If so, how can I solve the problem?

Here are some attachments including: the problem report, the orignal 2D spectrum for 5 files.

<img width="1227" alt="report" src="https://github.com/pypeit/PypeIt-development-suite/assets/116858817/5b2f4d12-e854-4f2d-8ec2-1b8a33366db1">

![LB 20180617 27634](https://github.com/pypeit/PypeIt-development-suite/assets/116858817/286eff41-548e-41d1-82ee-6124601ecad2)

![LB 20180617 28291](https://github.com/pypeit/PypeIt-development-suite/assets/116858817/a8db48c1-ea90-4ee7-aa80-517f415b56e9)
![LB 20180617 28380](https://github.com/pypeit/PypeIt-development-suite/assets/116858817/e580c7d7-e39b-4064-855b-a90b1eba014a)
![LB 20180617 28459](https://github.com/pypeit/PypeIt-development-suite/assets/116858817/d606184b-fbe1-4cb8-9804-2722d4a7fe84)

![LB 20180617 28189](https://github.com/pypeit/PypeIt-development-suite/assets/116858817/36c3074e-eae3-4efa-9eae-8015fe172a32)

**Comment by fgscc** [comment]
<img width="1402" alt="截屏2023-10-05 16 16 06" src="https://github.com/pypeit/PypeIt-development-suite/assets/116858817/f540e8d9-1fee-4739-a12f-87c55b505e25">
some details about the report.

**Comment by profxj** [comment]
please join the PypeIt Users Slack and discuss there.

It's easier for these types of issues than GitHub

thx
